import "./globals.css";
import { Inter } from "next/font/google";
// import GraphqlProvider from "./GraphqlProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {modal}
        {children}
        {/* <GraphqlProvider>{children}</GraphqlProvider> */}
      </body>
    </html>
  );
}
